version: '3.9'

networks:
  hadoop-net:
    driver: overlay

# Define TODOS los archivos de configuración aquí
configs:
  core-site.xml:
    file: ./DataNode-NodeManager/Config-files/core-site.xml
  hdfs-site-namenode.xml:
    file: ./NameNode/Config-files/hdfs-site-namenode.xml
  hdfs-site-datanode.xml:
    file: ./DataNode-NodeManager/Config-files/hdfs-site-datanode.xml
  yarn-site-resourcemanager.xml:
    file: ./ResourceManager/Config-files/yarn-site-resourcemanager.xml
  yarn-site-nodemanager.xml:
    file: ./DataNode-NodeManager/Config-files/yarn-site-nodemanager.xml
  hadoop-env.sh:
    file: ./DataNode-NodeManager/Config-files/hadoop-env.sh
  ssh-keys:
    file: ./ssh/authorized_keys

services:

  # ----------------------
  # NameNode (Manager)
  # ----------------------
  namenode:
    image: namenode-image:latest
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop-net
    configs:
      # --- INICIO DE LA CORRECCIÓN ---
      - source: core-site.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: hdfs-site-namenode.xml
        target: /opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      - source: hadoop-env.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      # --- FIN DE LA CORRECCIÓN ---
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      endpoint_mode: vip 
      placement:
        constraints:
          - node.role == manager
    user: root

  # ----------------------
  # ResourceManager (Manager)
  # ----------------------
  resourcemanager:
    image: resourcemanager-image:latest
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - "8088:8088"
    networks:
      - hadoop-net
    configs:
      # --- INICIO DE LA CORRECCIÓN ---
      - source: core-site.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: yarn-site-resourcemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/yarn-site.xml
      - source: hadoop-env.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      # --- FIN DE LA CORRECCIÓN ---
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      endpoint_mode: vip 
      placement:
        constraints:
          - node.role == manager
    user: root

  # ----------------------
  # DataNode + NodeManager (Workers)
  # ----------------------
  dnnm:
    image: dnnm-image:latest
    # El hostname aquí es menos relevante porque Swarm gestiona los nombres
    # hostname: dnnm-extra
    command: /opt/bd/start-daemons.sh
    networks:
      - hadoop-net
    configs:
      - source: core-site.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: yarn-site-nodemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/yarn-site.xml
      - source: hdfs-site-datanode.xml
        target: /opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      # --- INICIO DE LA CORRECCIÓN ---
      - source: hadoop-env.sh
        target: /opt/bd/hadoop/etc/hadoop/hadoop-env.sh
      # --- FIN DE LA CORRECCIÓN ---
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 3
    user: root
