version: '3.9'

networks:
  hadoop-net:
    driver: overlay

configs:
  core-site.xml:
    file: ./DataNode-NodeManager/Config-files/core-site.xml
  yarn-site-nodemanager.xml:
    file: ./DataNode-NodeManager/Config-files/yarn-site-nodemanager.xml
  hdfs-site-datanode.xml:
    file: ./DataNode-NodeManager/Config-files/hdfs-site-datanode.xml
  ssh-keys:
    file: ./ssh/authorized_keys   # <-- Archivo con claves públicas de todos los nodos

services:

  # ----------------------
  # NameNode (Manager)
  # ----------------------
  namenode:
    image: namenode-image:latest
    hostname: namenode
    command: /opt/bd/start-daemons.sh
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - hadoop-net
    configs:
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ----------------------
  # ResourceManager (Manager)
  # ----------------------
  resourcemanager:
    image: resourcemanager-image:latest
    hostname: resourcemanager
    command: /opt/bd/start-daemons.sh
    ports:
      - "8088:8088"
    networks:
      - hadoop-net
    configs:
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      placement:
        constraints:
          - node.role == manager

  # ----------------------
  # DataNode + NodeManager (Workers)
  # ----------------------
  dnnm:
    image: dnnm-image:latest
    hostname: dnnm-extra
    command: /opt/bd/start-daemons.sh
    networks:
      - hadoop-net
    configs:
      - source: core-site.xml
        target: /opt/bd/hadoop/etc/hadoop/core-site.xml
      - source: yarn-site-nodemanager.xml
        target: /opt/bd/hadoop/etc/hadoop/yarn-site.xml
      - source: hdfs-site-datanode.xml
        target: /opt/bd/hadoop/etc/hadoop/hdfs-site.xml
      - source: ssh-keys
        target: /home/hdadmin/.ssh/authorized_keys
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 30
      #placement:
        #constraints:
          #- node.role == worker
